# Generated by Django 5.1.6 on 2025-03-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventory_last_updated_inventory_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact',
            field=models.CharField(default='Unknown Contact', max_length=255),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default='noemail@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(),
        ),
    ]
